import type { ProjectCase } from "@/types/portfolio";

export const projects = [
  {
    slug: "quizlab-if",
    title: "QuizLab IF — Plataforma de quizzes gamificados em tempo real",
    shortTitle: "QuizLab IF",
    category: "Full Stack · Educação",
    status: "Em desenvolvimento",
    summary: "Aplicação educacional com criação de quizzes, salas ao vivo, autenticação, pontuação e ranking.",
    role: "Desenvolvimento full stack",
    collaboration: "Frontend e API apresentados como um único produto.",
    context: ["O projeto busca tornar atividades de revisão mais interativas para professores e estudantes da Rede Federal."],
    contributions: ["Construção do frontend em Next.js.", "API em AdonisJS com autenticação e persistência.", "Comunicação em tempo real para salas e pontuação."],
    decisions: [{ problem: "Sincronizar participantes durante uma sessão.", decision: "Separar frontend e API e usar Socket.io para eventos em tempo real.", tradeoff: "A solução exige gerenciar estado de conexão e reconexão além das chamadas REST." }],
    technologies: ["Next.js", "TypeScript", "AdonisJS", "PostgreSQL", "Socket.io"],
    evidence: ["Repositórios públicos de frontend e API com documentação de funcionalidades e stack."],
    limitations: ["Não há alegação de implantação institucional ou quantidade de usuários."],
    learnings: ["Modelagem de uma experiência multiusuário com comunicação em tempo real."],
    links: [
      { label: "Frontend", href: "https://github.com/invencaosts/quizlab-app", kind: "code" },
      { label: "API", href: "https://github.com/invencaosts/quizlab-api", kind: "code" },
    ],
  },
  {
    slug: "observatorio-grilagem-terras",
    title: "Observatório Grilagem de Terras Ariovaldo Umbelino de Oliveira — Plataforma Web GIS para monitoramento territorial",
    shortTitle: "Observatório Grilagem de Terras",
    category: "Web GIS · Bolsa CNPq",
    status: "Em desenvolvimento",
    summary: "Plataforma acadêmica para importar, visualizar e validar dados geoespaciais relacionados à grilagem de terras.",
    role: "Bolsista e desenvolvedor do projeto",
    collaboration: "Projeto acadêmico ativo com bolsa CNPq.",
    context: ["O sistema organiza camadas e casos geoespaciais para apoiar análise territorial."],
    contributions: ["Aplicação web e API para mapas e camadas.", "Persistência geoespacial com PostgreSQL/PostGIS.", "Fluxos de acesso, auditoria, importação e processamento assíncrono."],
    decisions: [{ problem: "Processar arquivos espaciais sem bloquear a aplicação.", decision: "Usar fila e armazenamento de objetos para desacoplar importação e processamento.", tradeoff: "A arquitetura adiciona serviços e complexidade operacional ao ambiente." }],
    technologies: ["Next.js", "NestJS", "PostGIS", "MapLibre", "BullMQ", "MinIO", "Docker"],
    evidence: ["Repositório público com arquitetura, módulos implementados e backlog documentado."],
    limitations: ["Deploy de produção não é declarado como concluído.", "Integrações externas e reforços de segurança permanecem no backlog documentado."],
    learnings: ["Modelagem de dados espaciais e processamento assíncrono em um produto full stack."],
    links: [{ label: "Código", href: "https://github.com/invencaosts/geoserver", kind: "code" }],
  },
  {
    slug: "demo-soc-ia",
    title: "Demonstração de SOC com detecção de ameaças assistida por IA",
    shortTitle: "Demo SOC com IA",
    category: "Segurança aplicada · IA",
    status: "Demonstração",
    summary: "Simulação técnica com API, dashboard, geração de logs e um modelo local para classificar padrões e acionar alertas.",
    role: "Desenvolvimento da demonstração",
    collaboration: "Projeto de estudo independente em cibersegurança.",
    context: ["Criada para tornar observável, em uma apresentação, o fluxo entre eventos, análise e alerta."],
    contributions: ["Separação em API, dashboard e painel de controle.", "Integração com modelo Qwen executado localmente via LM Studio.", "Simulação e visualização do fluxo de alertas."],
    decisions: [{ problem: "Executar a análise sem depender de um serviço externo de IA.", decision: "Usar um modelo local via LM Studio.", tradeoff: "A demonstração passa a depender da capacidade da máquina e não representa um SOC de produção." }],
    technologies: ["Python", "Qwen", "LM Studio", "APIs", "Dashboard"],
    evidence: ["Código e README públicos descrevem os três serviços da demonstração."],
    limitations: ["É uma simulação; não há alegação de precisão, produção ou ausência de falsos positivos."],
    learnings: ["Comunicação de conceitos de segurança e integração local de modelos de linguagem."],
    links: [{ label: "Código", href: "https://github.com/invencaosts/demo_palestra_cybersecurity", kind: "code" }],
  },
] satisfies ProjectCase[];

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
